



name: Build on PR

on:
  pull_request:
    branches:
      - master
      - branch1
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'
      
      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: db:generate
        
      - name: Run Build
        run: npm run build
